"use client";

import React from "react";
import Link from "next/link";
import { Navbar } from "@/components/Navbar";
import { ComplianceDisclosure } from "@/components/ui/ComplianceDisclosure";
import { useLanguage } from "@/context/LanguageContext";
import { Scale, AlertCircle } from "lucide-react";

export default function TermsPage() {
  const { lang, setLang } = useLanguage();

  return (
    <main className="min-h-screen bg-slate-50 text-slate-900 flex flex-col justify-between">
      <div>
        <Navbar />

        {/* Hero */}
        <section className="bg-[#001c38] text-white py-16 px-6 lg:px-10 border-b border-slate-800">
          <div className="max-w-4xl mx-auto space-y-4">
            <div className="inline-flex items-center gap-2 px-3 py-1 bg-secondary/20 border border-secondary/40 rounded-full text-secondary text-xs font-bold uppercase tracking-wider">
              <Scale size={14} className="text-secondary" />
              {lang === "es" ? "Términos Legales de Uso" : "Terms of Service"}
            </div>
            <h1 className="text-3xl md:text-5xl font-black tracking-tight leading-tight">
              {lang === "es" ? "Términos y Condiciones de Uso" : "Terms & Conditions"}
            </h1>
            <p className="text-slate-300 text-sm md:text-base leading-relaxed max-w-2xl">
              {lang === "es"
                ? "Términos que rigen el uso del portal web, calculadoras interactivas y solicitudes de consulta de AB Global Consulting."
                : "Terms governing the use of the website, interactive insurance tools, and consultation requests provided by AB Global Consulting."}
            </p>
            <div className="pt-2 flex items-center gap-4 text-xs text-slate-400">
              <span>{lang === "es" ? "Vigencia: 2026" : "Effective: 2026"}</span>
              <span>•</span>
              <button
                onClick={() => setLang(lang === "es" ? "en" : "es")}
                className="text-secondary font-bold hover:underline"
              >
                {lang === "es" ? "Read in English (EN)" : "Leer en Español (ES)"}
              </button>
            </div>
          </div>
        </section>

        {/* Body */}
        <section className="max-w-4xl mx-auto px-6 lg:px-10 py-16">
          <div className="bg-white rounded-3xl p-8 md:p-12 shadow-sm border border-slate-200 space-y-10 leading-relaxed text-sm text-slate-700">
            
            <div className="p-5 bg-amber-50 rounded-2xl border border-amber-200 text-amber-900 text-xs flex items-start gap-3">
              <AlertCircle size={18} className="text-amber-600 shrink-0 mt-0.5" />
              <p>
                <strong>{lang === "es" ? "Aviso Importante:" : "Important Advisory Notice:"}</strong>{" "}
                {lang === "es"
                  ? "Este portal web ofrece contenido educativo, simulaciones financieras y acceso a consultas diagnósticas. Ninguna información en este sitio constituye una oferta vinculante o póliza de seguro emitida."
                  : "This portal provides educational illustrations and access to consultations. Nothing on this website constitutes a binder, policy issuance, or guarantee of underwriting approval."}
              </p>
            </div>

            <div className="space-y-3">
              <h2 className="text-xl font-bold text-slate-900">
                1. {lang === "es" ? "Naturaleza de los Servicios" : "Nature of Services"}
              </h2>
              <p>
                {lang === "es"
                  ? "AB Global Consulting ofrece servicios de asesoría y orientación en seguros de vida (IUL), anualidades, planificación patrimonial militar y gastos finales. La emisión formal de pólizas está sujeta a las normas de suscripción de las compañías aseguradoras representadas."
                  : "AB Global Consulting provides independent advisory and illustration services across Indexed Universal Life (IUL), annuities, military asset protection, and final expense solutions. Formal policy issuance is subject to carrier underwriting requirements."}
              </p>
            </div>

            <div className="space-y-3">
              <h2 className="text-xl font-bold text-slate-900">
                2. {lang === "es" ? "Calculadoras y Simuladores Interactivos" : "Calculators & Interactive Simulators"}
              </h2>
              <p>
                {lang === "es"
                  ? "Las proyecciones mostradas en nuestras calculadoras (incluyendo el Simulador IUL y el Escudo Militar) son modelos matemáticos hipotéticos basados en tasas de rendimiento asumidas y no garantizan resultados futuros exactos."
                  : "Projections generated by interactive calculators (including the IUL Simulator and Military Asset Shield) are hypothetical illustrations based on user-entered parameters and do not guarantee future cash values or dividends."}
              </p>
            </div>

            <div className="space-y-3">
              <h2 className="text-xl font-bold text-slate-900">
                3. {lang === "es" ? "Licenciatura y Jurisdicción" : "Licensing & Jurisdiction"}
              </h2>
              <p>
                {lang === "es"
                  ? "Angel Burgos es un profesional con licencia 0215 del Estado de Florida (Lic. #G328926 / Código de Agente WFG: F6D9U). Los servicios se ofrecen principalmente para residentes de Florida y Puerto Rico."
                  : "Angel Burgos is a State Licensed 0215 Insurance Practitioner (FL License: #G328926 / WFG Agent Code: F6D9U), providing advisory services in authorized jurisdictions."}
              </p>
            </div>

            <div className="text-center pt-6">
              <Link
                href="/"
                className="inline-block px-6 py-3 bg-slate-900 hover:bg-secondary text-white font-bold text-xs rounded-xl shadow transition-all"
              >
                ← {lang === "es" ? "Volver al Inicio" : "Back to Home"}
              </Link>
            </div>
          </div>
        </section>
      </div>

      <ComplianceDisclosure />
    </main>
  );
}
